### ISSUE TITLE
Cannot add Technical Skills 

### ISSUE THREAD

**Issue by AnMnv** [siduck/quickcv#2]
**Cannot add Technical Skills even in editing mode of Demo**

![image](https://github.com/siduck/quickcv/assets/72667694/10551831-ff12-41c6-9aa9-55f9784e21c0)
![image](https://github.com/siduck/quickcv/assets/72667694/e66e6d1f-88ee-4cfb-a74f-f2913c8f223f)

**Comment by siduck** [comment]
what do  you mean cant add? just click the add button and a new field will be visible

![image](https://github.com/siduck/quickcv/assets/59060246/ca921296-fbb5-4cac-8a44-0f38801cae7f)

**Comment by AnMnv** [comment]
As you can see on the first screenshot above, I copied the last icon 3 times in the end, but on the preview page there are only 3 blank gray squircle? What am I doing wrong?

**Comment by AnMnv** [comment]
Made pull request with corrections

**Comment by siduck** [comment]
the PR is merged
