### ISSUE TITLE
Make it possible to add custom icons

### ISSUE THREAD

**Issue by gordonn** [siduck/quickcv#5]

**Comment by siduck** [comment]
for skills section?

**Comment by gordonn** [comment]
Yep for Technical Skills and Hobbies.

**Comment by siduck** [comment]
there's a way to do it, just click on demo and then see the editor's skills section. Although i'm thinking about adding an icon picker

**Comment by gordonn** [comment]
> there's a way to do it, just click on demo and then see the editor's skills section. Although i'm thinking about adding an icon picker

Yes however it only applies to certain icons and additional images cant be added

**Comment by siduck** [comment]
> > there's a way to do it, just click on demo and then see the editor's skills section. Although i'm thinking about adding an icon picker
> 
> Yes however it only applies to certain icons and additional images cant be added

all icons from iconify can be added tho, just need the write name
